# ~/.ansible/tasks/sssd-manage.yaml
---
- hosts: all
  gather_facts: true
  gather_subset:
    - local
  vars:
    role_path: "/playbook-share/supporto-os/roles/"
  tasks:

    - name: Print AC
      debug:
        msg: "AC active"
      when:  ansible_local.supportoosunix.software.ac | bool
