---
- name: Clona una vm V2C
  hosts: all
  vars:
    vm_name: "{{ vm | default('foo') }}"

  tasks:
  
    - name: Get all VMs as JSON
      ansible.builtin.command: kubectl get vm -A -o json
      register: vms_raw
      changed_when: false
          
    - name: Parse JSON
      ansible.builtin.set_fact:
        vms_json: "{{ vms_raw.stdout | from_json }}"
                
    - name: Extract namespace for a specific VM name
      ansible.builtin.set_fact:
        vm_namespace: >-
          {{
            (vms_json
             | json_query("items[?metadata.name=='" ~ vm_name ~ "'].metadata.namespace")
             | first)
             | default('NOT_FOUND')
          }}

    - name: Extract namespace for a specific VM name
      ansible.builtin.set_fact:
        vm_json: >-
          {{
            (vms_json
             | json_query("items[?metadata.name=='" ~ vm_name ~ "']")
             | first)
             | default('NOT_FOUND')
          }}

    
    - name: Extract PVC claim names referenced by the VM (KubeVirt)
      ansible.builtin.set_fact:
        vm_claims: >-
          {{
            (vm_json
            | json_query("spec.template.spec.volumes[?persistentVolumeClaim].persistentVolumeClaim.claimName"))
            | default([])
          }}


    - name: Get pvc as json
      ansible.builtin.command: kubectl get pvc -n "{{ vm_namespace }}" -o json
      register: pvc_raw

    - name: Parse JSON
      ansible.builtin.set_fact:
        pvc_json:  "{{ pvc_raw.stdout | from_json }}"

    - name: Set pvc name
      ansible.builtin.set_fact:
        pvc_name_origin: >-
          {{
            (pvc_json
            | json_query(".items[].spec.volumeName"))
            | default([])
          }}

    - debug:
        msg: "{{ pvc_name_origin }}"

