#!/bin/bash

# Questo script è usato per ripristinare i volumi di un nodo

help() {
echo "Help page

  $0 è usato per ripristinare i volumi di un nodo

  $0 [OPTION] [ARGUMENT]

  OPTION:

    --dry-run
      Print dei comandi senza eseguirli
    --all
      Delete plex for all volumes attached to host
    --volume
      Specifica un volume
    --host
      Specifica l'hostname nella forma FQDN
        
  EXAMPLE:

    Esegue il comando su un volume puntuale rimuovendo dal plex
    il nodo specificato

      $0 --volume myvol --host myhost.mydoamin

    Esegue il comando su un volume puntuale rimuovendo dal plex
    il nodo da cui lancio lo script

      $0 --volume myvol

    Esegue il comando su tutti i volumi rimuovendo dal plex
    il nodo specificato

      $0 --host myhost.mydoamin

    Esegue il comando su tutti i volumi rimuovendo dal plex
    il nodo da cui lancio lo script

      $0 --all
        "
        exit 0
}

dryrun() {
    if [[ "$dry-run" == true ]]; then
        echo -e "\e[33m[dry-run]\e[0m $*"
    else
        eval "$@"
    fi
}

# Clear var
help=""
all=""
volume=""
host=""

while [[ $# -gt 0 ]]; do
key="$1"

    if [[ "$key" == --* ]]; then
        varname="${key/--/}"

        # Se il prossimo argomento è un'altra opzione o è vuoto, allora è un flag
        if [[ -z "$2" || "$2" == --* ]]; then
            declare "$varname=true"
            shift
        else
            declare "$varname=\"$2\""
            shift 2
        fi
    else
        echo "Argomento non riconosciuto: $1"
        shift
    fi
done

if [[ "help" == true || -z ${all} && -z ${volume} ]]; then
  help
fi

# Se un host non viene specificato assume che l'host sia il nodo da cui si lancia il comando
if [[ -z ${host} ]]; then
    host=$(hostname)
fi

# Se il volume non è specificato li cerca tutti
volume_list=$(mktemp)
if [[ -z ${volume} ]]; then
# Lista volumi
    dctl volume list | grep Degraded | grep ${host} | awk '{print $1}' > $volume_list
elif [[ -n ${all} ]]; then
    echo ${volume} > $volume_list 
fi



for vol in $(cat $volume_list); do
    
    # Localizza il plex da eliminare
    plex=$(dctl volume describe ${vol} | tail -n 2 | grep ${host} |awk '{print $1}'| awk -F . '{print $2}')

    # Rimozione del nodo Failed dal plex
    echo Delete plex ${vol}
    dryrun dctl volume plex-delete ${vol} $plex &>/dev/null && echo -e "\e[32mSUCCESS\e[0m"
    sleep 60
    
#    # Controlla che il plex è stato rimosso
#    while dctl volume describe ${vol} | grep PendingDelete &>/dev/null; do
#        echo "Disk deletion in progress"
#        sleep 1
done

    watch "dctl volume list | grep Degraded | grep ${host} | awk '{print $1}'" 

for vol in $(cat $volume_list); do
    # Ripristina il mirror count a 2
    echo Update mirror count
    dryrun dctl volume update ${vol} -m 2 &>/dev/null && echo -e "\e[32mSUCCESS\e[0m"
    sleep 5 
    
#    # Attende il completamento del resync
#    until dctl volume describe ${vol} | grep Resyncing &>/dev/null; do
#        echo "Waiting in syncronization"
#        sleep 10
#    done
done

until for i in $(dctl volume list | grep dmtew12isp005t-m1.syssede.systest.sanpaoloimi.com | awk '{print $1}'); do dctl volume describe $i | grep Resyncing; done; do echo "" ; sleep 10; done

rm -f $volume_list
