- name: Config auto-update /etc/hosts
  hosts: all
  gather_facts: false
  vars:
    file: "{{ name | default('foo') }}"
    dir: "{{ path | default('bar') }}"
    mode: "{{ perm | default('0750') }}"
    user: "{{ owner | default(ansible_user_id) }}"
    group: "{{ owner | default(ansible_user_id) }}"


  tasks:
    - name: Istruzioni per eseguire il playbook
      fail:
        msg: "-e 'name=<file_name> path=</path/on/target> owner=<file_owner>'"
      run_once: true
      when: file == 'foo' or dir == 'bar' or user == 'foobar'

    - name: Create directory tree if absent
      file:
        path: "{{ dir }}"
        state: directory
        mode: "{{ mode }}"
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: deploy file
      copy:
        src: "/home/B0N4022/.ansible/files/{{ file }}"
        dest: "{{ dir }}"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "{{ mode }}"
        force: yes
