---
- name: Convert diamanti volumes from block to filesystem
  hosts: all
  tasks:

    - name: Provide pvc
      command: >
        kubectl get pvc 
        -n "{{ namespace }}" 
        -o custom-columns=name:.metadata.name
        --no-headers
      register: resources_name

    - name: Convert from output to list
      set_fact:
        resources: "{{ resources_name.stdout_lines }}"

    - name: Block looping by resources
      block:

        - name: Generate UUID
          set_facl:
            g_uuid: "{{ lookup('ansible.builtin.uuid') }}"

        - name: Gathering pvc info
          command: >
            kubectl get pvc 
            -n {{ namespace }} 
            {{ items }}
            -o json
          register: raw_old_pvc

        - name: Convert json in ansible object
          set_fact:
            old_pvc: "{{ raw_old_pvc.stdout | from json }}"

        - name: Create new volume
          command: >
            dctl -o json volume create "pvc-{{ g_uuid }}" 
            -s "{{ old-pvc.items[].spec.resources.requests.storage }}" 
            --sc "{{ old-pvc.items[].spec.storageClassName }}" 
            --sel "{{ old-pvc.items[].spec.storageClassName }}"=true 
            -m 2
          register: raw_new_pvc

          
        - name: Convert json in ansible object
          set_fact:
            new_pvc: "{{ raw_new_pvc.stdout | from json }}"

        - name: Create temporary file
          tempfile:
            state: file
            suffix: ".yaml"
          register: tmpfile

        - name: Deploy pvc spec file
          template:
            src: /home/B0N4022/.ansible/files/k8s_pvc.j2
            dest: "{{ tmpfile.path }}"

        - name: Create new k8s pvc
          command: kubectl create -f "{{ tmpfile.path }}"

        - name: Delete temporary file
          template:
            path: "{{ tmpfile.path }}"
            state: absent

        - name: Check PV's storageClass
          command: kubectl get pv "{{ new_pvc.name }}" -o custom-columns=sc:.spec.storageClassName --no-headers
          register: new_pv_sc

        - name: Fix output
          set_facl:
            pv_sc: "{{ new_pv_sc.stdout | default('') | trim }}"

        - name: Patch PV
          command: >
            kubectl patch pv "{{ new_pvc.name }}"
            --type merge
            -p '{"spec":{"storageClassName": "{{ old-pvc.items[].spec.storageClassName }}"}}'

        - name: Create temporary file
          tempfile:
            state: file
            suffix: ".yaml"
          register: tmpfile

        - name: Deploy pvc spec file
          template:
            src: /home/B0N4022/.ansible/files/storageclass-migrator.j2
            dest: "{{ tmpfile.path }}"

        - name: Create k8s pod
          command: kubectl create -f "{{ tmpfile.path }}"

        - name: Delete temporary file
          file:
            path: "{{ tmpfile.path }}"
            state: absent

      loop: "{{ resources }}"
      when: resources | length > 0
