---
- name: Check VM on V2C clusters
  hosts: localhost
  gather_facts: false

  vars:
    vm_name: "{{ vm }}"
    ssh_dir: "{{ lookup('env','HOME') }}/.ssh"
    cluster_keys: >-
      {{ lookup('pipe', "ls -1 " + ssh_dir + " | grep -E '^d'") 
      .split('\n') | list }}
    nodes_suffixes: ["m1", "m2", "m3"]
    domain: "syssede.systest.sanpaoloimi.com"
    found_flag: "/tmp/vm_found_flag_{{ vm_name }}"

  tasks:

    - name: Rimuovi flag precedente
      file:
        path: "{{ found_flag }}"
        state: absent

    - name: Debug – elenco cluster trovati
      debug:
        var: cluster_keys

    - name: Loop su tutti i cluster
      vars:
        cluster: "{{ item }}"
      loop: "{{ cluster_keys }}"

      block:

        - name: Salta questo cluster se VM già trovata
          debug:
            msg: "VM già trovata, salto cluster {{ cluster }}"
          when: lookup('file', found_flag, errors='ignore') is truthy

        - name: Loop nodi
          vars:
            fqdn: "{{ cluster }}-{{ node }}.{{ domain }}"
          loop: "{{ nodes_suffixes }}"
          loop_control:
            loop_var: node
          block:

          - name: Salta nodo se VM già trovata
            debug:
              msg: "Flag trovato, salto nodo {{ fqdn }}"
            when: lookup('file', found_flag, errors='ignore') is truthy

          - name: Ping nodo
            command: "ping -c1 -W1 {{ fqdn }}"
            register: ping_res
            ignore_errors: true

          - name: Nodo non raggiungibile
            debug:
              msg: "Nodo {{ fqdn }} non raggiungibile"
            when: ping_res.rc != 0

          - name: Esegui kubectl remoto
            when: ping_res.rc == 0
            command: >
              ssh -q -l diamanti -i {{ ssh_dir }}/{{ cluster }}
              -o StrictHostKeyChecking=no
              {{ fqdn }}
              "dlogin &>/dev/null &&
              kubectl get vm -A | grep -iw '{{ vm_name }}'"
            register: vm_out
            ignore_errors: true

          - name: Se trovata
            when: vm_out.stdout | length > 0
            block:
              - name: Scrivi flag
                file:
                  path: "{{ found_flag }}"
                  state: touch

              - name: Messaggio trovato
                debug:
                  msg: "{{ vm_name }} found on {{ cluster }}"

            rescue:
              - debug:
                msg: "Errore su {{ fqdn }}"

          - name: Non controllare altri nodi se uno risponde
            meta: break
            when: ping_res.rc == 0

      rescue:
        - debug:
          msg: "Errore durante controllo cluster {{ cluster }}"

    - name: Mostra risultato finale
      debug:
        msg: "{{ vm_name }} NOT found"
      when: not lookup('file', found_flag, errors='ignore') is truthy
