---
- name: Fix Service Network Configuration
  hosts: master
  become: yes

  pre-tasks:

    - name: "Diamanti login"
      changed_when: false
      check_mode: true
      run_once: true
      ansible.builtin.command: dctl -s "{{ cluster_ip }}" login -u {{ dctl_user }} -p {{ dctl_password }}

    - name: "Calcola se il nodo k8s è un master"
      register: master_node
      changed_when: false
      check_mode: true
      ansible.builtin.shell:
        cmd: kubectl get node {{ ansible_fqdn }} --no-headers -o custom-columns="is-master:.metadata.labels.diamanti-node-role\.kubernetes\.io\/master"
        executable: /bin/bash

    - name: "Calcola la versione SW"
      ansible.builtin.shell:
        cmd: "dctl -o json cluster status | jq '.status.nodeStatus[].info.swVersion' | uniq"
        executable: "/bin/bash"
        warn: false
      become: false
      register: cluster_status
      changed_when: false

  tasks:

    - name: Modifica la configurazione della rete di overlay
      when: master_node.stdout == "true" and "4.1.2" in cluster_status.stdout
      ansible.builtin.replace:
        path: "{{ item }}"
        regexp: '10\.0\.0\.0/24'
        replace: '10.0.0.0/16'
      loop:
        - /usr/local/bin/netconf.sh
        - /etc/kubernetes/apiserver

    - name: Restart apiserver
      when: master_node.stdout == "true" and "4.1.2" in cluster_status.stdout
      ansible.builtin.systemd:
        name: apiserver
        state: restarted
    