---
- name: Node healthchecker
  hosts: all
  gather_facts: false
  tasks:
    - name: Pinging host "{{ inventory_hostname }}"
      ping:
      register: ping_res

    - name: Check ssh connection
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22 
        delay: 6 
        state: started
        timeout: 10
      delegate_to: localhost
      register: healtcheck

    - name: Printing ping_res
      debug:
        var: ping_res

    - name: Printing healtcheck
      debug:
        var: healtcheck

    - name: Printing result
      debug:
        msg: "Healthcheck succesfull on node {{ inventory_hostname }}"
      when: not ping_res.failed and not healtcheck.failed
