#!/bin/sh
# Copyright 2023 Cohesity Inc.
#
# Author: Kaushik Nimbalkar
 
# This script fetches information from the Kubernetes cluster regarding the
# Cohesity deployment.
 
# Usage: ./k8s-info-fetcher.sh [-u|--user_ns <ns-name>]
# user_ns: Additional user namespace to fetch info about
 
while [ "$#" -gt 0 ]; do
    case $1 in
        -u|--user_ns) user_ns=$2; shift;;
        *) echo "Unknown parameter passed: $1"; exit 1 ;;
    esac
    shift
done
 
cohesity_ns=$(kubectl get ns -o=name | grep "cohesity-.*" | cut -d "/" -f 2)
output_dir=k8s-info-fetcher-output-$(date +%s)
mkdir -p $output_dir
 
f_get_cluster_resource_info() {
  kubectl get $1 -o wide > $output_dir/get_$1.log
  kubectl get $1 -o json > $output_dir/get_$1_json.log
  kubectl describe $1 > $output_dir/describe_$1.log
}
 
f_get_ns_resource_info() {
  kubectl get $1 -n $2 -o wide > $output_dir/$2/get_$1.log
  kubectl get $1 -n $2 -o json > $output_dir/$2/get_$1_json.log
  kubectl describe $1 -n $2 > $output_dir/$2/describe_$1.log
}
 
echo "Fetching info on cluster scoped resources"
f_get_cluster_resource_info "nodes"
f_get_cluster_resource_info "ns"
f_get_cluster_resource_info "sc"
f_get_cluster_resource_info "pv"
f_get_cluster_resource_info "crd"
f_get_cluster_resource_info "clusterrolebinding"
f_get_cluster_resource_info "clusterrole"
if [ -z $cohesity_ns ]; then
    echo "Cohesity namespace not found."
else
    echo "Fetching info on Cohesity namespace $cohesity_ns"
    mkdir -p $output_dir/$cohesity_ns
    f_get_ns_resource_info "pods" $cohesity_ns
    f_get_ns_resource_info "svc" $cohesity_ns
    f_get_ns_resource_info "deployment" $cohesity_ns
    f_get_ns_resource_info "daemonset" $cohesity_ns
    f_get_ns_resource_info "limits" $cohesity_ns
    f_get_ns_resource_info "secret" $cohesity_ns
    f_get_ns_resource_info "sa" $cohesity_ns
    echo "Fetching velero logs"
    kubectl logs deployment/velero -n $cohesity_ns > $output_dir/$cohesity_ns/velero.log
fi
if [ ! -z $user_ns ]; then
    mkdir -p $output_dir/$user_ns
    echo "Fetching info on user namespace $user_ns"
    f_get_ns_resource_info "pods" $user_ns
    f_get_ns_resource_info "svc" $user_ns
    f_get_ns_resource_info "deployment" $user_ns
    f_get_ns_resource_info "daemonset" $user_ns
    f_get_ns_resource_info "limits" $user_ns
    f_get_ns_resource_info "pvc" $user_ns
fi
tar cf "$output_dir.tar" $output_dir
rm -r $output_dir
