---
- name: Postconfig by Mauden
  hosts: all
  become: true

  tasks:
    - name: Gathering facts
      setup:
        gather_subset: local

# {{{ APACHE configuration fixer
    - name: APACHE configuration fixer
      block:

        - name: Creazione directory log se non esiste
          file:
            path: /cloni/logs/mb
            state: directory
            mode: '0755'

        - name: Deploy script swa_fixer.sh
          template:
            src: ../templates/swa_fixer.sh.j2
            dest: /usr/local/bin/swa_fixer.sh
            mode: '0755'
            owner: root
            group: root

        - name: Deploy systemd service swa_fixer
          template:
            src: ../templates/swa_fixer.service.j2
            dest: /etc/systemd/system/swa_fixer.service
            mode: '0644'
            owner: root
            group: root
          register: service

        - name: Reload systemd
          systemd:
            daemon_reload: true
          when: service.changed

        - name: Enable swa_fixer service
          systemd:
            name: swa_fixer.service
            enabled: yes

      when: ansible_local.supportoosunix.general.web | default(false) | bool
# }}}

# {{{ JBOSS configuration fixer
    - name: JBoss configuration fixer
      block:
        - name: Get admin server via grep
          shell: |
            find /spimi/jboss/ -type f -name host.xml -exec grep 'port="9999"' {} \; \
            | sed -E 's/.*host="([^"]+)".*/\1/'
          register: admin_server_cmd
          changed_when: false
        - set_fact:
            admin_server: "{{ admin_server_cmd.stdout_lines[0] }}"
            service_lo: "{{ service | lower }}"
        - debug:
            msg: "Admin server = {{ admin_server }}"
        - name: Find domain.xml on admin server
          find:
            paths: /spimi/jboss/
            patterns: domain.xml
            recurse: yes
            file_type: file
          delegate_to: "{{ admin_server }}"
          register: domain_xml_files
          changed_when: false
        - name: Replace default-interface any -> public for {{ service_lo }}Sockets
          replace:
            path: "{{ item.path }}"
            regexp: '(<socket-binding-group\b[^>]*\bname="{{ service_lo }}Sockets"[^>]*\bdefault-interface=")any(")'
            replace: '\1public\2'
            backup: yes
          delegate_to: "{{ admin_server }}"
          loop: "{{ domain_xml_files.files }}"
          register: domain_xml_replace
      when: ansible_local.supportoosunix.general.jboss | default(false) | bool == true
# }}}

    - name: fix icinga
      block:
        - name: Delete daemon logging
          replace:
            path: /etc/rsyslog.d/90-google.conf
            regexp: '^daemon,?'
            replace: ''
          failed_when: false
        - name: Reloading icinga
          systemd:
            name: icinga2
            state: reloaded

    - name: enable fstrim if supported
      block:
        - name: Check if devices supports TRIM
          command: lsblk --discard --noheadings --output NAME,DISC-GRAN
          register: trim_check
          changed_when: false
        - name: Set variable trim_supported
          set_fact:
            trim_supported: "{{ trim_check.stdout_lines | select('search', '[1-9][0-9]*[BKMGTP]') | list | length > 0 }}"
        - name: Running one shot trim
          command: fstrim -a
          when: trim_supported
        - name: Ensure fstrim override directory exists
          file:
            path: /etc/systemd/system/fstrim.timer.d
            state: directory
            mode: '0755'
          when: trim_supported
        - name: Override fstrim default configuration
          template:
            src: ../templates/fstrim-override.j2
            dest: /etc/systemd/system/fstrim.timer.d/override.conf
            owner: root
            group: root
            mode: '0644'
          when: trim_supported
        - name: Daemon reload
          systemd:
            daemon_reload: true
          when: trim_supported
        - name: Enable and start fstrim.timer
          systemd:
            name: fstrim.timer
            enabled: true
            state: started
          when: trim_supported

    - name: manage network dispatcher script
      block:
        - name: Set correct hostname for vm
          ansible.builtin.hostname:
           name: "{{ inventory_hostname }}"
        - name: Delete google dispatcher script if present
          file:
            path: /etc/NetworkManager/dispatcher.d/google_hostname.sh
            state: absent
        - name: Deploy script dispatcher 99-fix-hosts
          ansible.builtin.template:
            src: ../templates/99-fix-hosts.j2
            dest: /etc/NetworkManager/dispatcher.d/99-fix-hosts
            owner: root
            group: root
            mode: '0755'
        - name: Daemon reload
          systemd:
            daemon_reload: true
        - name: Restart NetworkManager service
          systemd:
            name: NetworkManager
            state: restarted
            enabled: true
