- name: Config auto-update /etc/hosts
  hosts: all
  gather_facts: false
  tasks:

    - name: deploy dispacher script
      copy:
        src: "/home/B0N4022/.ansible/files/86-update-hosts"
        dest: "/etc/NetworkManager/dispatcher.d/86-update-hosts"
        owner: root
        group: root
        mode: '755'
        force: yes

    - name: Restart NetworkManager
      ansible.builtin.systemd:
         name: NetworkManager
         state: restarted
