---
- name: Cloning pvc
  hosts: all
  gather_facts: true
  vars:
    vm_name: test

  pre_tasks:
    - name: Test
      fail:
        msg: "use -e vm_name=my-vm"
      when: vm_name == 'test'


  tasks:
    - name: Extracting namespace
      command: 
        cmd: kubectl get vm -A -o jsonpath='{range .items[?(@.metadata.name=="{{ vm_name }}")]}{.metadata.namespace}{"\n"}{end}'
      register: namespace_ex
    
    - name: Setting namespace
      set_fact:
        namespace: "{{ namespace_ex.stdout }}"
    
    - name: Print namespace
      debug:
        var: namespace

    - name: Extracting pvc info
      command:
        cmd: kubectl get -n "{{ namespace }}" pvc  -o jsonpath='{.items[*].metadata.name}{"\n"}'
      register: pvc_ex

    - name: convert output in list
      set_fact:
        pvc_list: "{{ pvc_ex.stdout_lines }}"





# dctl volume create tommaso-test -s 1GB --sel m1m2 -m 2 --sc m1m2 --sel m1m2=true | awk 'NR>1 {print $1}'
