# ~/.ansible/tasks/sssd-manage.yaml
---
- hosts: all
  gather_facts: true
  gather_subset: local
  vars:
    role_path: "/home/B0N4022/.ansible/roles/"
  tasks:
    - name: Imposta valore di default per state
      set_fact:
        state: "{{ state | default('test') }}"

    - name: Mostra istruzioni se lo stato è di default
      debug:
        msg:
          - Non hai specificato la variabile 'state'.
          - Usa uno dei seguenti comandi:
          -  ansible-playbook sssd_manage.yml -e state=present   # per installare
          - ansible-playbook sssd_manage.yml -e state=absent    # per disinstallare
          - 
          - DIREZIONE:
          - DOF
          - DFRM
          - EUR
          - FID
          - SIT
      when: state == 'test'

    - name: Remove AC
      include_role:
        name: "{{ role_path }}AC-remove"
      when: ( ansible_local.supportoosunix.software.ac | bool )  and ( state  == 'present')
  
    - name: Configura sssd
      include_role:
        name: "{{ role_path }}config-AD-registration"
      vars:    
        direzione: "{{ dir | default('SIT') }}"
        ambiente: "{{ ansible_local.supportoosunix.general.env }}"
        poc: "{{ ansible_local.supportoosunix.general.poc }}"
        override_config: "{{ force | default('False') }}"
      when: state == 'present'

    - name: Disinstalla sssd
      include_role:
        name: "{{ role_path }}del-config-AD-registration"
      when: state == 'absent'



# ansible-playbook -i <server>, myPlaybookRunRole.yml
#
# DIREZIONE
#
# DOF
# DFRM
# EUR
# FID
# SIT
#
# AMBIENTE
#
# gestione
# produzione
# collaudo
# test
# sviluppo
# formazione
# uat
# laboratorio
#
# OVERRIDE_CONFIG
#
# True (yes) <--- Rigenera il file /etc/sssd-registration.conf come fosse una prima installazione
# False (no) <--- Non e' una prima installazione e si vuol mantenere intatto il file /etc/sssd-registration.conf
#
# POC
#
# True (yes)
# False (no)
